version: '3.4'

services:
  mysqldata:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "0.0.0.0"
    ports:
      - "3306:3306"
    volumes:
      - botgenerator:/c/ProgramData/MySQL/MySQL\ Server 8.0/Data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
  
  botservice-api:
    build:
      context: .
      dockerfile: Services/BotService/BotService.API/Dockerfile
    depends_on:
      - rabbitmq
      - mysqldata
  
volumes:
  botgenerator:
    external: false