version: '3.4'

services:
  mysqldata:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "0.0.0.0"
    ports:
      - "3306:3306"
    volumes:
      - botgenerator:/c/ProgramData/MySQL/MySQL\ Server 8.0/Data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
  
  nginxapigw:
    image: nginx
    volumes:
      - ./ApiGateways/nginx:/etc/nginx/conf.d/
    ports:
      - "8000:80"
  
  botservice-api:
    build:
      context: .
      dockerfile: Services/BotService/BotService.API/Dockerfile
    ports:
      - "81:80"
      - "5001:5001"
    depends_on:
      - rabbitmq
      - mysqldata
  
  telegram-api:
    build:
      context: .
      dockerfile: Services/TelegramReceiver/TelegramReceiver.API/Dockerfile
    ports:
      - "82:80"
      - "5101:5001"
    depends_on:
      - rabbitmq
      - mysqldata
  
volumes:
  botgenerator:
    external: false